[2024-03-19 12:57:29,486: INFO: main: STAGE >>>> Data Ingestion Stage started]
[2024-03-19 12:57:29,488: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-19 12:57:29,490: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 12:57:29,491: INFO: common: created directory at: artifacts]
[2024-03-19 12:57:29,491: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-19 12:57:29,491: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1wTvlJjWavZS7kV9dlWGqYUw1-wLbZvyQ/view?usp=sharing into the file artifacts/data_ingestion/data.zip]
[2024-03-19 12:57:31,029: ERROR: main: module 'collections' has no attribute 'Callable']
Traceback (most recent call last):
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 28, in download_file
    raise e
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 23, in download_file
    gdown.download(prefix+file_id, zip_download_dir)
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 32, in get_url_from_gdrive_confirmation
    soup = bs4.BeautifulSoup(line, features="html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 167, in feed
    parser.feed(markup)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 112, in handle_decl
    self.soup.endData(Doctype)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1040, in __getattr__
    return self.find(tag)
           ^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1278, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1299, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1596, in __init__
    self.text = self._normalize_search_value(text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1601, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
[2024-03-19 13:39:43,769: INFO: main: STAGE >>>> Data Ingestion Stage started]
[2024-03-19 13:39:43,814: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-19 13:39:43,868: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 13:39:43,868: INFO: common: created directory at: artifacts]
[2024-03-19 13:39:43,887: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-19 13:39:43,888: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1wTvlJjWavZS7kV9dlWGqYUw1-wLbZvyQ/view?usp=sharing into the file artifacts/data_ingestion/data.zip]
[2024-03-19 13:40:03,898: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1wTvlJjWavZS7kV9dlWGqYUw1-wLbZvyQ/view?usp=sharing into the file artifacts/data_ingestion/data.zip]
[2024-03-19 13:40:03,898: ERROR: main: module 'zipfile' has no attribute 'Zipfile']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip_file()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 35, in extract_zip_file
    with zipfile.Zipfile(self.config.local_data_file, 'r') as zip_ref:
AttributeError: module 'zipfile' has no attribute 'Zipfile'
[2024-03-20 12:15:49,754: INFO: main: STAGE >>>> Data Ingestion Stage started]
[2024-03-20 12:15:49,758: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 12:15:49,790: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 12:15:49,790: INFO: common: created directory at: artifacts]
[2024-03-20 12:15:49,790: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-20 12:15:49,790: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1wTvlJjWavZS7kV9dlWGqYUw1-wLbZvyQ/view?usp=sharing into the file artifacts/data_ingestion/data.zip]
[2024-03-20 12:15:51,200: ERROR: main: module 'collections' has no attribute 'Callable']
Traceback (most recent call last):
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 28, in download_file
    raise e
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 23, in download_file
    gdown.download(prefix+file_id, zip_download_dir)
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 32, in get_url_from_gdrive_confirmation
    soup = bs4.BeautifulSoup(line, features="html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 167, in feed
    parser.feed(markup)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 112, in handle_decl
    self.soup.endData(Doctype)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1040, in __getattr__
    return self.find(tag)
           ^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1278, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1299, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1596, in __init__
    self.text = self._normalize_search_value(text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1601, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
[2024-03-20 12:17:17,006: INFO: main: STAGE >>>> Data Ingestion Stage started]
[2024-03-20 12:17:17,008: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 12:17:17,009: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 12:17:17,009: INFO: common: created directory at: artifacts]
[2024-03-20 12:17:17,010: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-20 12:17:17,010: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1wTvlJjWavZS7kV9dlWGqYUw1-wLbZvyQ/view?usp=sharing into the file artifacts/data_ingestion/data.zip]
[2024-03-20 12:17:18,138: ERROR: data_ingestion: Error occurred during file download: module 'collections' has no attribute 'Callable']
Traceback (most recent call last):
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id, zip_download_file)
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 32, in get_url_from_gdrive_confirmation
    soup = bs4.BeautifulSoup(line, features="html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 167, in feed
    parser.feed(markup)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 112, in handle_decl
    self.soup.endData(Doctype)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1040, in __getattr__
    return self.find(tag)
           ^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1278, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1299, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1596, in __init__
    self.text = self._normalize_search_value(text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1601, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
[2024-03-20 12:17:18,142: ERROR: main: module 'collections' has no attribute 'Callable']
Traceback (most recent call last):
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 28, in download_file
    raise e
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id, zip_download_file)
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 32, in get_url_from_gdrive_confirmation
    soup = bs4.BeautifulSoup(line, features="html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 167, in feed
    parser.feed(markup)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 112, in handle_decl
    self.soup.endData(Doctype)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1040, in __getattr__
    return self.find(tag)
           ^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1278, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1299, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1596, in __init__
    self.text = self._normalize_search_value(text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1601, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
[2024-03-20 12:19:06,157: INFO: main: STAGE >>>> Data Ingestion Stage started]
[2024-03-20 12:19:06,159: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 12:19:06,161: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 12:19:06,161: INFO: common: created directory at: artifacts]
[2024-03-20 12:19:06,161: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-20 12:19:06,161: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1wTvlJjWavZS7kV9dlWGqYUw1-wLbZvyQ/view?usp=sharing into the file artifacts/data_ingestion/data.zip]
[2024-03-20 12:19:07,214: ERROR: data_ingestion: Error occurred during file download: module 'collections' has no attribute 'Callable']
Traceback (most recent call last):
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id, zip_download_file)
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 32, in get_url_from_gdrive_confirmation
    soup = bs4.BeautifulSoup(line, features="html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 167, in feed
    parser.feed(markup)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 112, in handle_decl
    self.soup.endData(Doctype)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1040, in __getattr__
    return self.find(tag)
           ^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1278, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1299, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1596, in __init__
    self.text = self._normalize_search_value(text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1601, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
[2024-03-20 12:19:07,218: ERROR: main: module 'collections' has no attribute 'Callable']
Traceback (most recent call last):
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 28, in download_file
    raise e
  File "/home/hemanth/only_ml/Kidney-Disease-Classification-Normal-Tumor/src/cnnClassifier/components/data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id, zip_download_file)
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/gdown/download.py", line 32, in get_url_from_gdrive_confirmation
    soup = bs4.BeautifulSoup(line, features="html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 167, in feed
    parser.feed(markup)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 112, in handle_decl
    self.soup.endData(Doctype)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1040, in __getattr__
    return self.find(tag)
           ^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1278, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1299, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1596, in __init__
    self.text = self._normalize_search_value(text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemanth/.local/lib/python3.11/site-packages/bs4/element.py", line 1601, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
